## Database Properties
spring.datasource.url=jdbc:mysql:///users-db?cloudSqlInstance=project-d3724b7f-300d-4698-8b8:us-central1:lab-users-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
spring.datasource.username=anavic
spring.datasource.password=Itesm.2019

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}